# railway.toml

[build]
  # Construir el frontend de React
  buildCommand = "cd sistema-pedidos-ui && npm install && npm run build && cd .."
  # Comando para recoger los archivos estáticos de Django
  postBuildCommand = "python manage.py collectstatic --noinput"

[deploy]
  # Comando para iniciar el servidor Django
  startCommand = "gunicorn sistema.wsgi:application --bind 0.0.0.0:$PORT"
  restartPolicyType = "ON_FAILURE"