# Generated by Django 5.2.7 on 2025-10-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apeliidos',
            new_name='apellidos',
        ),
    ]
